project:
  type: website
  output-dir: docs

website:
  title: "Text Utilities"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Reference"
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  title: textutils Module
  style: pkgdown
  dir: reference
  package: textutils

  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Function Documentation
      desc: Common helper functions for basic text preprocessing and analysis.
      contents:
        - textutils.word_count
        - textutils.reverse_text
        - textutils.most_common_word
        - textutils.remove_punctuation
